# Generated by Django 6.0.6 on 2026-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
    ]
