# Generated by Django 6.0.6 on 2026-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
