# Generated by Django 6.0.6 on 2026-06-18 10:27

from django.db import migrations
from datetime import date


def create_default_project(apps, schema_editor):
    Project = apps.get_model('tracker_app', 'Project')
    Issue = apps.get_model('tracker_app', 'Issue')

    default_project = Project.objects.create(
        name='Тестовый проект',
        description='Проект для существуюших задач',
        start_date = date.today()
    )
    Issue.objects.all().update(project=default_project)


def rollback_default_project(apps, schema_editor):
    Project = apps.get_model('tracker_app', 'Project')
    Project.objects.filter(name='Тестовый проект').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_project_issue_project'),
    ]

    operations = [
        migrations.RunPython(create_default_project, rollback_default_project)
    ]
