# Generated by Django 6.0.6 on 2026-06-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_alter_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type_old',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker_app.type', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ManyToManyField(blank=True, related_name='issues', to='tracker_app.type', verbose_name='Тип'),
        ),
    ]
