# Generated by Django 6.0.6 on 2026-06-11 12:11

from django.db import migrations


def transfer_types(apps, schema_editor):
    Issue = apps.get_model('tracker_app', 'Issue')
    for issue in Issue.objects.all():
        issue.issue_type.set([issue.issue_type_old])


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('tracker_app', 'Issue')
    for issue in Issue.objects.all():
        types = issue.issue_type.all()
        if types:
            issue.issue_type_old = types.first()
            issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_issue_type_old_remove_issue_issue_type_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]