# Generated by Django 6.0.6 on 2026-06-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_alter_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
